version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
    - "5432:5432"
    networks:
      - postgres
    env_file:
      - docker.env
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    env_file:
      - docker.env
 
  nestjs-api:
    build:
      context: .
      target: create-build
    command: npm run typeorm:migrate
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge