version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
 
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
 
  nestjs-api:
    build:
      context: .
      target: create-build
    command: sh -c "npm run typeorm:run-migrations && npm run start:dev"
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge