version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
    - "5432:5432"
    env_file:
    - docker.env
    networks:
    - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    env_file:
    - docker.env
    networks:
    - postgres

  nestjs-api:
    build:
      context: .
    command: sh -c "npm run typeorm:run-migrations && npm run start:dev"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge